Subway.NZ.Web/Controllers/ExpressOrderingController.cs
using Subway.NZ.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Subway.NZ.Data;
using System.Threading.Tasks;

namespace Subway.NZ.Web.Controllers
{
    public class ExpressOrderingController : Controller
    {
        private readonly DataFacade DataFacade;

        public ExpressOrderingController()
        {
            // to replace with DI
            this.DataFacade = new Data.DataFacade();
        }

        public async Task<ActionResult> Index()
        {
            OrderingModel model = await GetModel();
            return View(model);
        }

        private async Task<OrderingModel> GetModel()
        {
            var model = new OrderingModel
            {
                Menu = await DataFacade.GetMenuAsync(),
                Lengths = await DataFacade.GetLengthsAsync(),
                Drinks = await DataFacade.GetDrinksAsync(),
                Sides = await DataFacade.GetSidesAsync(),
                AdditionalItems = await DataFacade.GetAdditionalItemsAsync(),
                Balance = new OrderingModel.CustomerBalance
                {
                    CardNumber = "1234567890123456",
                    RewardsBalance = 3.28m,
                    GiftsBalance = 30m
                }
            };

            var p1 = model.Menu.Categories.First().Products.ElementAt(0);
            var p2 = model.Menu.Categories.First().Products.ElementAt(1);

            model.Cart = new Data.Models.Cart()
            {
                SelectedStore = new Data.Models.Cart.Store { StoreId = 1, StoreName = "Some store somewhere" },
                Items = new List<Data.Models.Cart.CartItem>
                 {
                    new Data.Models.Cart.CartItem { Code = p1.Code, ProductName = p1.Name, Quantity = 1, Price = p1.Price, ImageUrl = p1.ImageUrl },
                    new Data.Models.Cart.CartItem { Code = p2.Code, ProductName = p2.Name, Quantity = 2, Price = p2.Price, ImageUrl = p2.ImageUrl }
                 },                
            };

            model.Stores = new List<Data.Models.Store>
            {
                new Data.Models.Store { SiteId = 1, Name = "London store", AcceptsCreditCards = true},
                new Data.Models.Store { SiteId = 2, Name = "Bristol store", AcceptsCreditCards = false},
            };


            model.RecentOrders = new List<Data.Models.Order>
            {
                new Data.Models.Order { OrderId = 12345, Date = DateTime.Now, Pickup = DateTime.Now.AddMinutes(30), Name = "Order 1",
                Items = new List<Data.Models.Cart.CartItem>
                 {
                    new Data.Models.Cart.CartItem { Code = p1.Code, ProductName = p1.Name, Quantity = 1, Price = p1.Price, ImageUrl = p1.ImageUrl },
                    new Data.Models.Cart.CartItem { Code = p2.Code, ProductName = p2.Name, Quantity = 2, Price = p2.Price, ImageUrl = p2.ImageUrl }
                 }},
                new Data.Models.Order { OrderId = 12346, Date = DateTime.Now, Pickup = DateTime.Now.AddMinutes(30), Name = "Order 2",
                Items = new List<Data.Models.Cart.CartItem>
                 {
                    new Data.Models.Cart.CartItem { Code = p1.Code, ProductName = p1.Name, Quantity = 1, Price = p1.Price, ImageUrl = p1.ImageUrl },
                    new Data.Models.Cart.CartItem { Code = p2.Code, ProductName = p2.Name, Quantity = 2, Price = p2.Price, ImageUrl = p2.ImageUrl }
                 }}
            };

            return model;
        }

        public async Task<ActionResult> Step2()
        {
            OrderingModel model = await GetModel();
            return View(model);
        }
        public async Task<ActionResult> Step3()
        {
            OrderingModel model = await GetModel();
            return View(model);
        }
        public async Task<ActionResult> Step4()
        {
            OrderingModel model = await GetModel();
            return View(model);
        }
        public async Task<ActionResult> Step5()
        {
            OrderingModel model = await GetModel();
            return View(model);
        }

        public async Task<ActionResult> School()
        {
            OrderingModel model = await GetModel();
            return View(model);
        }

        public async Task<ActionResult> MyLastOrder()
        {
            OrderingModel model = await GetModel();
            return View(model);
        }
    }
}

Subway.NZ.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Subway.NZ.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Subway.NZ.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Subway.NZ.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Subway.NZ.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome to Subway Express";
}

<div class="green-panel margin-top-30">
    <div class="row text-center">
        <img src="~/Images/logo-green-bg.png" />
    </div>
    <div class="row  margin-top-30">
        <div class="col-md-6 text-center">
            <div class="col-md-12 white-panel">
                <img src="~/Images/home-individual.png" />
                <h2>Individuals or Catering</h2>
                <p><a class="btn btn-default" href="@Url.Action("Index", "ExpressOrdering")">Order now</a></p>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="col-md-12 white-panel">
                <img src="~/Images/home-school.png" />
                <h2>Subway &reg; School Lunch Programme</h2>
                <p><a class="btn btn-default" href="@Url.Action("School", "ExpressOrdering")">Order now</a></p>
            </div>
        </div>
    </div>
</div>